cloud:
  aws:
    credentials:
      access-key: AKIA24JPHQU6HJRTK2EU
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: innovatesolutions-virtualschool


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

